stages:
  - setup
  - test

# Set up the Python environment using pip
before_script:
  - echo "Setting up Python environment"
  - python -m venv venv
  - source venv/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt  # Install dependencies listed in your requirements file

# Test stage
pytest:
  stage: test
  script:
    - source venv/bin/activate
    - pytest --maxfail=5 --disable-warnings -q --tb=short --junitxml=pytest_results.xml  # Run tests and generate XML report
  artifacts:
    paths:
      - pytest_results.xml  # Store the JUnit XML result file as an artifact

# Optional: Cache pip packages for faster builds
cache:
  paths:
    - venv/
    - .cache/pip/
